# Generated by Django 2.1.4 on 2018-12-16 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('phone', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='turn',
            name='nomad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felix_web.User'),
        ),
        migrations.AddField(
            model_name='turn',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='felix_web.Session'),
        ),
        migrations.AddField(
            model_name='turn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
