# Generated by Django 2.1.4 on 2018-12-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felix_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='resolved_by_human',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.NullBooleanField(),
        ),
    ]
