# Generated by Django 2.1.4 on 2018-12-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('felix_web', '0002_auto_20181216_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='status',
            new_name='success',
        ),
        migrations.AddField(
            model_name='session',
            name='nomad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='felix_web.User'),
            preserve_default=False,
        ),
    ]
