# Generated by Django 2.1.4 on 2018-12-16 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('felix_web', '0003_auto_20181216_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='lat',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turn',
            name='lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
