# Generated by Django 2.1.4 on 2018-12-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('felix_web', '0004_auto_20181216_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turn',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
